/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment2;

import java.util.Arrays;

/**
 *
 * @author b4018943
 */
public class FarmManagementGUI extends javax.swing.JFrame 
{
    User user = null;
    FarmList farms = null;
    //FarmList farms = Core.myAccount.getFarms();
    
    /**
     * Creates new form FarmList
     * @param user
     */
    public FarmManagementGUI(User user) 
    {
        initComponents();
        this.user = user;
        lblUsername.setText(user.getUsername());
        //System.out.print(Core.myAccount.getFarms().get(0).getName());
        farmList.setListData(user.getFarms().toArray());
    }
     
    //ignore for now. do not remove
    public void getFarms()
    {
        //farms = Core.myAccount.getFarms();
    }
    public void showFarms()
    {
        /*for(int i = 0; i < Core.myAccount.getFarms().size(); i++)
        {
            System.out.println(Core.myAccount.getFarms().get(i).getName());
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        btnAddFarm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        farmList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogout.setText("Log Out");
        btnLogout.setName("btnLogout"); // NOI18N

        lblUsername.setText("Username goes here");
        lblUsername.setName("lblUsername"); // NOI18N

        btnAddFarm.setText("+ Add Farm");
        btnAddFarm.setName("btnAddFarm"); // NOI18N

        farmList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(farmList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsername)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnAddFarm))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(lblUsername))
                .addGap(48, 48, 48)
                .addComponent(btnAddFarm)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFarm;
    private javax.swing.JButton btnLogout;
    private javax.swing.JList farmList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
