/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment2;

/**
 *
 * @author Andy
 */
public class HardwareManagementGUI extends javax.swing.JFrame 
{
    User user = null;
    FarmList farms = new FarmList();
    FieldList fields = new FieldList();
    Farm selectedFarm = null;
    Field selectedField = null;
    
    /**
     * Creates new form HardwareManagementGUI
     * @param user
     */
    public HardwareManagementGUI(User user) 
    {
        initComponents();
        this.user = user;
        farms = user.getFarms();
        lblUsername.setText(user.getUsername());
        getFarmList();
    }
    
    public final void getFarmList()
    {
        farmList.setListData(farms.toArray());
    }
    
    public void setSelectedFarm()
    {
        int index = farmList.getSelectedIndex();
        for (int i = 0; i < farms.size(); i++)
        {
            selectedFarm = farms.get(i);
            if (selectedFarm.getName().equals(farmList.getModel().getElementAt(index).toString()))
            {
                showFarmFields();
                break;
            }
        }
    }
    
    public void setSelectedField()
    {
        int index = fieldList.getSelectedIndex();
        for (int i = 0; i < fields.size(); i++)
        {
            selectedField = fields.get(i);
            if (selectedField.getName().equals(fieldList.getModel().getElementAt(index).toString()))
            {
                break;
            }
        }
    }
    
    public void showFarmFields()
    {
        fields = selectedFarm.getFields();
        fieldList.setListData(fields.toArray());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldStationDialog = new javax.swing.JDialog();
        lblFieldStation = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtFieldStationLocation = new javax.swing.JTextField();
        txtFieldStationPhone = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtFieldStationCode = new javax.swing.JTextField();
        btnFieldStationAdd = new javax.swing.JButton();
        btnFieldStationCancel = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        sensorList = new javax.swing.JList();
        btnAddSensor = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        addSensorDialog = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        btnSensorAdd = new javax.swing.JButton();
        btnSensorCancel = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        lblFields = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        farmList = new javax.swing.JList();
        btnFieldStationSetup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fieldList = new javax.swing.JList();

        fieldStationDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        fieldStationDialog.setMinimumSize(new java.awt.Dimension(400, 430));
        fieldStationDialog.setPreferredSize(new java.awt.Dimension(400, 430));

        lblFieldStation.setText("Field name");

        jLabel16.setText("Location (coordinates):");

        jLabel17.setText("Phone Number: ");

        jLabel18.setText("Unique Access Code:");

        btnFieldStationAdd.setText("Ok");
        btnFieldStationAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFieldStationAddActionPerformed(evt);
            }
        });

        btnFieldStationCancel.setText("Cancel");
        btnFieldStationCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFieldStationCancelActionPerformed(evt);
            }
        });

        jLabel19.setText("Sensors:");

        jScrollPane9.setViewportView(sensorList);

        btnAddSensor.setText("+ Add sensor");
        btnAddSensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSensorActionPerformed(evt);
            }
        });

        jButton1.setText("Edit Selected Sensor");

        javax.swing.GroupLayout fieldStationDialogLayout = new javax.swing.GroupLayout(fieldStationDialog.getContentPane());
        fieldStationDialog.getContentPane().setLayout(fieldStationDialogLayout);
        fieldStationDialogLayout.setHorizontalGroup(
            fieldStationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldStationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fieldStationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(txtFieldStationLocation)
                    .addComponent(txtFieldStationPhone)
                    .addComponent(txtFieldStationCode)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fieldStationDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFieldStationCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFieldStationAdd))
                    .addGroup(fieldStationDialogLayout.createSequentialGroup()
                        .addGroup(fieldStationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFieldStation)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addGroup(fieldStationDialogLayout.createSequentialGroup()
                                .addComponent(btnAddSensor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        fieldStationDialogLayout.setVerticalGroup(
            fieldStationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldStationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFieldStation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldStationLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldStationPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldStationCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fieldStationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSensor)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fieldStationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFieldStationAdd)
                    .addComponent(btnFieldStationCancel))
                .addContainerGap())
        );

        addSensorDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addSensorDialog.setTitle("Add sensor");
        addSensorDialog.setMinimumSize(new java.awt.Dimension(275, 280));
        addSensorDialog.setPreferredSize(new java.awt.Dimension(275, 280));

        jLabel20.setText("Location (coordinates):");

        jLabel21.setText("Type:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Air Temperature", "Pressure", "Soil Moisture", "Acidity", "Soil Temperature", "Light Sensor" }));

        jLabel22.setText("Frequency: ");

        btnSensorAdd.setText("Ok");

        btnSensorCancel.setText("Cancel");

        jCheckBox1.setText("Enabled?");

        javax.swing.GroupLayout addSensorDialogLayout = new javax.swing.GroupLayout(addSensorDialog.getContentPane());
        addSensorDialog.getContentPane().setLayout(addSensorDialogLayout);
        addSensorDialogLayout.setHorizontalGroup(
            addSensorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addSensorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addSensorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addSensorDialogLayout.createSequentialGroup()
                        .addGap(0, 139, Short.MAX_VALUE)
                        .addComponent(btnSensorCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSensorAdd))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addSensorDialogLayout.createSequentialGroup()
                        .addGroup(addSensorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addSensorDialogLayout.setVerticalGroup(
            addSensorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSensorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(addSensorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSensorAdd)
                    .addComponent(btnSensorCancel))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFields.setText("Fields:");

        btnLogout.setText("Log Out");
        btnLogout.setName("btnLogout"); // NOI18N

        lblUsername.setText("username");
        lblUsername.setName("lblUsername"); // NOI18N

        farmList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                farmListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(farmList);

        btnFieldStationSetup.setText("Manage Field Station/ Sensors");
        btnFieldStationSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFieldStationSetupActionPerformed(evt);
            }
        });

        jLabel1.setText("Farms:");

        fieldList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(fieldList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUsername)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblFields)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFieldStationSetup))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 31, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFields)
                    .addComponent(btnFieldStationSetup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void farmListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_farmListMouseClicked
        setSelectedFarm();
    }//GEN-LAST:event_farmListMouseClicked

    private void btnFieldStationSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFieldStationSetupActionPerformed
        if ((!fieldList.isSelectionEmpty()) && (!fieldList.isSelectionEmpty()))
        {
            lblFieldStation.setText(selectedField.getName() + " station setup");
            txtFieldStationLocation.setText(selectedField.getFieldStation().getGPSCoord().toString());
            txtFieldStationPhone.setText(selectedField.getFieldStation().getPhoneNumber());
            txtFieldStationCode.setText(selectedField.getFieldStation().getUniqueCode());
            sensorList.setListData(selectedField.getFieldStation().getSensors().toArray());
            fieldStationDialog.setVisible(true);
        }
    }//GEN-LAST:event_btnFieldStationSetupActionPerformed

    private void fieldListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldListMouseClicked
        setSelectedField();
    }//GEN-LAST:event_fieldListMouseClicked

    private void btnFieldStationAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFieldStationAddActionPerformed
        //add
    }//GEN-LAST:event_btnFieldStationAddActionPerformed

    private void btnFieldStationCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFieldStationCancelActionPerformed
        fieldStationDialog.dispose();
    }//GEN-LAST:event_btnFieldStationCancelActionPerformed

    private void btnAddSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSensorActionPerformed
        addSensorDialog.setVisible(true);
    }//GEN-LAST:event_btnAddSensorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog addSensorDialog;
    private javax.swing.JButton btnAddSensor;
    private javax.swing.JButton btnFieldStationAdd;
    private javax.swing.JButton btnFieldStationCancel;
    private javax.swing.JButton btnFieldStationSetup;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSensorAdd;
    private javax.swing.JButton btnSensorCancel;
    private javax.swing.JList farmList;
    private javax.swing.JList fieldList;
    private javax.swing.JDialog fieldStationDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblFieldStation;
    private javax.swing.JLabel lblFields;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JList sensorList;
    private javax.swing.JTextField txtFieldStationCode;
    private javax.swing.JTextField txtFieldStationLocation;
    private javax.swing.JTextField txtFieldStationPhone;
    // End of variables declaration//GEN-END:variables
}
